// This code was generated by robots, do not modify

#pragma once

#include "game.h"


enum Textures_{
   Textures_test2,
   
   Textures_COUNT
};

struct AssetTextures{
   EGATexture* array[Textures_COUNT] = { 0 };

   EGATexture* test2 = nullptr;
   
};
extern AssetTextures Textures;

enum Palettes_{
   Palettes_test,
   
   Palettes_COUNT
};

struct AssetPalettes{
   EGAPalette* array[Palettes_COUNT] = { 0 };

   EGAPalette* test = nullptr;
   
};
extern AssetPalettes Palettes;


void assetsStartup();
