#include "stdafx.h"
#include "input.h"

#include <SDL_scancode.h>

int SCANCODE_A = SDL_SCANCODE_A;
int SCANCODE_B = SDL_SCANCODE_B;
int SCANCODE_C = SDL_SCANCODE_C;
int SCANCODE_D = SDL_SCANCODE_D;
int SCANCODE_E = SDL_SCANCODE_E;
int SCANCODE_F = SDL_SCANCODE_F;
int SCANCODE_G = SDL_SCANCODE_G;
int SCANCODE_H = SDL_SCANCODE_H;
int SCANCODE_I = SDL_SCANCODE_I;
int SCANCODE_J = SDL_SCANCODE_J;
int SCANCODE_K = SDL_SCANCODE_K;
int SCANCODE_L = SDL_SCANCODE_L;
int SCANCODE_M = SDL_SCANCODE_M;
int SCANCODE_N = SDL_SCANCODE_N;
int SCANCODE_O = SDL_SCANCODE_O;
int SCANCODE_P = SDL_SCANCODE_P;
int SCANCODE_Q = SDL_SCANCODE_Q;
int SCANCODE_R = SDL_SCANCODE_R;
int SCANCODE_S = SDL_SCANCODE_S;
int SCANCODE_T = SDL_SCANCODE_T;
int SCANCODE_U = SDL_SCANCODE_U;
int SCANCODE_V = SDL_SCANCODE_V;
int SCANCODE_W = SDL_SCANCODE_W;
int SCANCODE_X = SDL_SCANCODE_X;
int SCANCODE_Y = SDL_SCANCODE_Y;
int SCANCODE_Z = SDL_SCANCODE_Z;

int SCANCODE_1 = SDL_SCANCODE_1;
int SCANCODE_2 = SDL_SCANCODE_2;
int SCANCODE_3 = SDL_SCANCODE_3;
int SCANCODE_4 = SDL_SCANCODE_4;
int SCANCODE_5 = SDL_SCANCODE_5;
int SCANCODE_6 = SDL_SCANCODE_6;
int SCANCODE_7 = SDL_SCANCODE_7;
int SCANCODE_8 = SDL_SCANCODE_8;
int SCANCODE_9 = SDL_SCANCODE_9;
int SCANCODE_0 = SDL_SCANCODE_0;

int SCANCODE_RETURN = SDL_SCANCODE_RETURN;
int SCANCODE_ESCAPE = SDL_SCANCODE_ESCAPE;
int SCANCODE_BACKSPACE = SDL_SCANCODE_BACKSPACE;
int SCANCODE_TAB = SDL_SCANCODE_TAB;
int SCANCODE_SPACE = SDL_SCANCODE_SPACE;

int SCANCODE_MINUS = SDL_SCANCODE_MINUS;
int SCANCODE_EQUALS = SDL_SCANCODE_EQUALS;
int SCANCODE_LEFTBRACKET = SDL_SCANCODE_LEFTBRACKET;
int SCANCODE_RIGHTBRACKET = SDL_SCANCODE_RIGHTBRACKET;
int SCANCODE_BACKSLASH = SDL_SCANCODE_BACKSLASH;
int SCANCODE_SEMICOLON = SDL_SCANCODE_SEMICOLON;
int SCANCODE_APOSTROPHE = SDL_SCANCODE_APOSTROPHE;

int SCANCODE_COMMA = SDL_SCANCODE_COMMA;
int SCANCODE_PERIOD = SDL_SCANCODE_PERIOD;
int SCANCODE_SLASH = SDL_SCANCODE_SLASH;

int SCANCODE_CAPSLOCK = SDL_SCANCODE_CAPSLOCK;

int SCANCODE_F1 = SDL_SCANCODE_F1;
int SCANCODE_F2 = SDL_SCANCODE_F2;
int SCANCODE_F3 = SDL_SCANCODE_F3;
int SCANCODE_F4 = SDL_SCANCODE_F4;
int SCANCODE_F5 = SDL_SCANCODE_F5;
int SCANCODE_F6 = SDL_SCANCODE_F6;
int SCANCODE_F7 = SDL_SCANCODE_F7;
int SCANCODE_F8 = SDL_SCANCODE_F8;
int SCANCODE_F9 = SDL_SCANCODE_F9;
int SCANCODE_F10 = SDL_SCANCODE_F10;
int SCANCODE_F11 = SDL_SCANCODE_F11;
int SCANCODE_F12 = SDL_SCANCODE_F12;

int SCANCODE_PRINTSCREEN = SDL_SCANCODE_PRINTSCREEN;
int SCANCODE_SCROLLLOCK = SDL_SCANCODE_SCROLLLOCK;
int SCANCODE_PAUSE = SDL_SCANCODE_PAUSE;
int SCANCODE_INSERT = SDL_SCANCODE_INSERT;

int SCANCODE_HOME = SDL_SCANCODE_HOME;
int SCANCODE_PAGEUP = SDL_SCANCODE_PAGEUP;
int SCANCODE_DELETE = SDL_SCANCODE_DELETE;
int SCANCODE_END = SDL_SCANCODE_END;
int SCANCODE_PAGEDOWN = SDL_SCANCODE_PAGEDOWN;
int SCANCODE_RIGHT = SDL_SCANCODE_RIGHT;
int SCANCODE_LEFT = SDL_SCANCODE_LEFT;
int SCANCODE_DOWN = SDL_SCANCODE_DOWN;
int SCANCODE_UP = SDL_SCANCODE_UP;

int SCANCODE_KP_DIVIDE = SDL_SCANCODE_KP_DIVIDE;
int SCANCODE_KP_MULTIPLY = SDL_SCANCODE_KP_MULTIPLY;
int SCANCODE_KP_MINUS = SDL_SCANCODE_KP_MINUS;
int SCANCODE_KP_PLUS = SDL_SCANCODE_KP_PLUS;
int SCANCODE_KP_ENTER = SDL_SCANCODE_KP_ENTER;
int SCANCODE_KP_1 = SDL_SCANCODE_KP_1;
int SCANCODE_KP_2 = SDL_SCANCODE_KP_2;
int SCANCODE_KP_3 = SDL_SCANCODE_KP_3;
int SCANCODE_KP_4 = SDL_SCANCODE_KP_4;
int SCANCODE_KP_5 = SDL_SCANCODE_KP_5;
int SCANCODE_KP_6 = SDL_SCANCODE_KP_6;
int SCANCODE_KP_7 = SDL_SCANCODE_KP_7;
int SCANCODE_KP_8 = SDL_SCANCODE_KP_8;
int SCANCODE_KP_9 = SDL_SCANCODE_KP_9;
int SCANCODE_KP_0 = SDL_SCANCODE_KP_0;
int SCANCODE_KP_PERIOD = SDL_SCANCODE_KP_PERIOD;

int SCANCODE_APPLICATION = SDL_SCANCODE_APPLICATION;
int SCANCODE_KP_EQUALS = SDL_SCANCODE_KP_EQUALS;