// This code was generated by robots, do not modify

#pragma once

#include "game.h"


enum Textures_{
   Textures_Dude,
   Textures_DudeNormals,
   Textures_GemCracked,
   Textures_GemEmpty,
   Textures_GemFilled,
   Textures_HeartEmpty,
   Textures_HeartFilled,
   Textures_ShittySword,
   Textures_SwordNormals,
   Textures_Tile,
   Textures_TileNormals,
   Textures_TinyHeartEmpty,
   Textures_TinyHeartFull,
   Textures_TinyStamCracked,
   Textures_TinyStamEmpty,
   Textures_TinyStamFull,
   
   Textures_COUNT
};

struct AssetTextures{
   Texture* array[Textures_COUNT] = { 0 };

   Texture* Dude = nullptr;
   Texture* DudeNormals = nullptr;
   Texture* GemCracked = nullptr;
   Texture* GemEmpty = nullptr;
   Texture* GemFilled = nullptr;
   Texture* HeartEmpty = nullptr;
   Texture* HeartFilled = nullptr;
   Texture* ShittySword = nullptr;
   Texture* SwordNormals = nullptr;
   Texture* Tile = nullptr;
   Texture* TileNormals = nullptr;
   Texture* TinyHeartEmpty = nullptr;
   Texture* TinyHeartFull = nullptr;
   Texture* TinyStamCracked = nullptr;
   Texture* TinyStamEmpty = nullptr;
   Texture* TinyStamFull = nullptr;
   
};
extern AssetTextures Textures;

enum Sprites_{
   Sprites_Dude,
   Sprites_Sword,
   Sprites_Tile,
   
   Sprites_COUNT
};

struct AssetSprites{
   Sprite* array[Sprites_COUNT] = { 0 };

   Sprite* Dude = nullptr;
   Sprite* Sword = nullptr;
   Sprite* Tile = nullptr;
   
};
extern AssetSprites Sprites;

enum Maps_{
   Maps_test,
   
   Maps_COUNT
};

struct AssetMaps{
   Map* array[Maps_COUNT] = { 0 };

   Map* test = nullptr;
   
};
extern AssetMaps Maps;

enum Weapons_{
   Weapons_Sword,
   
   Weapons_COUNT
};

struct AssetWeapons{
   Weapon* array[Weapons_COUNT] = { 0 };

   Weapon* Sword = nullptr;
   
};
extern AssetWeapons Weapons;

enum MoveSets_{
   MoveSets_Sword,
   
   MoveSets_COUNT
};

struct AssetMoveSets{
   MoveSet* array[MoveSets_COUNT] = { 0 };

   MoveSet* Sword = nullptr;
   
};
extern AssetMoveSets MoveSets;

enum DudeTemplates_{
   DudeTemplates_Dude,
   
   DudeTemplates_COUNT
};

struct AssetDudeTemplates{
   DudeTemplate* array[DudeTemplates_COUNT] = { 0 };

   DudeTemplate* Dude = nullptr;
   
};
extern AssetDudeTemplates DudeTemplates;


void assetsStartup();
