// This code was generated by robots, do not modify

#pragma once

#include "reflection.h"


// DudeState ----------------------------
extern TypeMetadata* meta_DudeState;
typedef enum DudeState DudeState;
template<>
struct Reflector<DudeState>{
   static TypeMetadata const* type() { return meta_DudeState; }
};


// TextureFlag_ ----------------------------
extern TypeMetadata* meta_TextureFlag_;
typedef enum TextureFlag_ TextureFlag_;
template<>
struct Reflector<TextureFlag_>{
   static TypeMetadata const* type() { return meta_TextureFlag_; }
};



// Coords ----------------------------
typedef struct Coords Coords;
extern TypeMetadata* meta_Coords;
template<>
struct Reflector<Coords>{
   static TypeMetadata const* type() { return meta_Coords; }
};


// Time ----------------------------
typedef struct Time Time;
extern TypeMetadata* meta_Time;
template<>
struct Reflector<Time>{
   static TypeMetadata const* type() { return meta_Time; }
};


// ColorRGB ----------------------------
typedef struct ColorRGB ColorRGB;
extern TypeMetadata* meta_ColorRGB;
template<>
struct Reflector<ColorRGB>{
   static TypeMetadata const* type() { return meta_ColorRGB; }
};


// ColorRGBA ----------------------------
typedef struct ColorRGBA ColorRGBA;
extern TypeMetadata* meta_ColorRGBA;
template<>
struct Reflector<ColorRGBA>{
   static TypeMetadata const* type() { return meta_ColorRGBA; }
};


// ColorRGBf ----------------------------
typedef struct ColorRGBf ColorRGBf;
extern TypeMetadata* meta_ColorRGBf;
template<>
struct Reflector<ColorRGBf>{
   static TypeMetadata const* type() { return meta_ColorRGBf; }
};


// ColorHSV ----------------------------
typedef struct ColorHSV ColorHSV;
extern TypeMetadata* meta_ColorHSV;
template<>
struct Reflector<ColorHSV>{
   static TypeMetadata const* type() { return meta_ColorHSV; }
};


// ColorRGBAf ----------------------------
typedef struct ColorRGBAf ColorRGBAf;
extern TypeMetadata* meta_ColorRGBAf;
template<>
struct Reflector<ColorRGBAf>{
   static TypeMetadata const* type() { return meta_ColorRGBAf; }
};


// EngineConstants ----------------------------
typedef struct EngineConstants EngineConstants;
extern TypeMetadata* meta_EngineConstants;
template<>
struct Reflector<EngineConstants>{
   static TypeMetadata const* type() { return meta_EngineConstants; }
};


// EngineState ----------------------------
typedef struct EngineState EngineState;
extern TypeMetadata* meta_EngineState;
template<>
struct Reflector<EngineState>{
   static TypeMetadata const* type() { return meta_EngineState; }
};


// Wall ----------------------------
typedef struct Wall Wall;
extern TypeMetadata* meta_Wall;
template<>
struct Reflector<Wall>{
   static TypeMetadata const* type() { return meta_Wall; }
};


// Light ----------------------------
typedef struct Light Light;
extern TypeMetadata* meta_Light;
template<>
struct Reflector<Light>{
   static TypeMetadata const* type() { return meta_Light; }
};


// Sprite ----------------------------
typedef struct Sprite Sprite;
extern TypeMetadata* meta_Sprite;
template<>
struct Reflector<Sprite>{
   static TypeMetadata const* type() { return meta_Sprite; }
};


// AttackSwing ----------------------------
typedef struct AttackSwing AttackSwing;
extern TypeMetadata* meta_AttackSwing;
template<>
struct Reflector<AttackSwing>{
   static TypeMetadata const* type() { return meta_AttackSwing; }
};


// MoveSet ----------------------------
typedef struct MoveSet MoveSet;
extern TypeMetadata* meta_MoveSet;
template<>
struct Reflector<MoveSet>{
   static TypeMetadata const* type() { return meta_MoveSet; }
};


// Weapon ----------------------------
typedef struct Weapon Weapon;
extern TypeMetadata* meta_Weapon;
template<>
struct Reflector<Weapon>{
   static TypeMetadata const* type() { return meta_Weapon; }
};


// DudeTemplate ----------------------------
typedef struct DudeTemplate DudeTemplate;
extern TypeMetadata* meta_DudeTemplate;
template<>
struct Reflector<DudeTemplate>{
   static TypeMetadata const* type() { return meta_DudeTemplate; }
};


// DudeSpawn ----------------------------
typedef struct DudeSpawn DudeSpawn;
extern TypeMetadata* meta_DudeSpawn;
template<>
struct Reflector<DudeSpawn>{
   static TypeMetadata const* type() { return meta_DudeSpawn; }
};


// Map ----------------------------
typedef struct Map Map;
extern TypeMetadata* meta_Map;
template<>
struct Reflector<Map>{
   static TypeMetadata const* type() { return meta_Map; }
};


// GameAssets ----------------------------
typedef struct GameAssets GameAssets;
extern TypeMetadata* meta_GameAssets;
template<>
struct Reflector<GameAssets>{
   static TypeMetadata const* type() { return meta_GameAssets; }
};


// GameStateDebug ----------------------------
typedef struct GameStateDebug GameStateDebug;
extern TypeMetadata* meta_GameStateDebug;
template<>
struct Reflector<GameStateDebug>{
   static TypeMetadata const* type() { return meta_GameStateDebug; }
};


// Int3 ----------------------------
typedef struct Int3 Int3;
extern TypeMetadata* meta_Int3;
template<>
struct Reflector<Int3>{
   static TypeMetadata const* type() { return meta_Int3; }
};


// Float2 ----------------------------
typedef struct Float2 Float2;
extern TypeMetadata* meta_Float2;
template<>
struct Reflector<Float2>{
   static TypeMetadata const* type() { return meta_Float2; }
};


// Float3 ----------------------------
typedef struct Float3 Float3;
extern TypeMetadata* meta_Float3;
template<>
struct Reflector<Float3>{
   static TypeMetadata const* type() { return meta_Float3; }
};


// Int2 ----------------------------
typedef struct Int2 Int2;
extern TypeMetadata* meta_Int2;
template<>
struct Reflector<Int2>{
   static TypeMetadata const* type() { return meta_Int2; }
};


// ConvexPoly ----------------------------
typedef struct ConvexPoly ConvexPoly;
extern TypeMetadata* meta_ConvexPoly;
template<>
struct Reflector<ConvexPoly>{
   static TypeMetadata const* type() { return meta_ConvexPoly; }
};


// Recti ----------------------------
typedef struct Recti Recti;
extern TypeMetadata* meta_Recti;
template<>
struct Reflector<Recti>{
   static TypeMetadata const* type() { return meta_Recti; }
};


// Rectf ----------------------------
typedef struct Rectf Rectf;
extern TypeMetadata* meta_Rectf;
template<>
struct Reflector<Rectf>{
   static TypeMetadata const* type() { return meta_Rectf; }
};


// Texture ----------------------------
typedef struct Texture Texture;
extern TypeMetadata* meta_Texture;
template<>
struct Reflector<Texture>{
   static TypeMetadata const* type() { return meta_Texture; }
};


// FBO ----------------------------
typedef struct FBO FBO;
extern TypeMetadata* meta_FBO;
template<>
struct Reflector<FBO>{
   static TypeMetadata const* type() { return meta_FBO; }
};

